export const problemsDB = {
    easy: [
        "Second Largest Element",
        "Third Largest Element",
        "Reverse an Array",
        "Reverse Array in Groups",
        "Rotate Array",
        "Three Great Candidates",
        "Max Consecutive Ones",
        "Move All Zeroes to End",
        "Wave Array",
        "Stock Buy and Sell - One Transaction",
        "Stock Buy and Sell - Multiple Transactions",
        "Remove Duplicates from Sorted Array",
        "Palindrome Check",
        "Reverse a String",
        "Reverse Words",
        "Check for Rotation",
        "Roman to integer",
        "Plus one",
        "Alternate Positive Negative",
        "Array Leaders",
        "Missing and Repeating in Array",
        "Missing Ranges of numbers",
        "Sum of all Subarray",
    ],

    medium: [
        "Next Permutation",
        "Majority Element",
        "Majority Element II",
        "Minimize the Heights II",
        "Maximum Subarray Sum",
        "Maximum Product Subarray",
        "Product of Array Except Self",
        "Subarray with Product Less Than K",
        "Split into three equal Sum segmants",
        "Maximum Consecutive 1s After Flipping 0s",
        "Last moment before ants fall out of plank",
        "Find 0 with farthest 1s in a Binary",
        "Intersection of Interval list",
        "Rearrange Array Element by sign",
        "Meeting Scheduler for two persons",
        "Longest Mountain Subarray",
        "Transform and sort array",
        "Minimum Swaps to group all ones",
        "Minimum moves to equalize array",
        "Minimum indices to equal even-odd sums",
        "Integer to Words",
        "Fizz Buzz",
        "Palindromic Sentence Check",
        "Isomorphic Strings",

    ],

    hard: [
        "Trapping Rain Water",
        "Maximum Circular Subarray Sum",
        "Smallest Missing Positive Number",
        "Jump Game",
        "Closest Subsequence Sum",
        "Smallest Non-Representable Sum",
        "Smallest Range having Elements from K-List",
        "Count Subarrays with K distinct elements",
        "Next Smallest Palindrome",
        "Maximum Sum Among All Rotation",
        "Repeatedly Remove Duplicates",
        "Multiply Two Strings",
        "Search Pattern (KMP Algorithm)",
        "Search Pattern (Rabin-Karp Algorithm)",
        "Shortest Common Supersequence"
    ]
};
